### ISSUE TITLE
add support for indexing thunk

### ISSUE THREAD

**Issue by tbenst** [tbenst/Thunks.jl#1]
could make a getindex function that returns a new thunk

**Comment by mcabbott** [comment]
Might be worth investigating what ChainRules does, if I understood the readme example correctly:
```
julia> using ChainRulesCore: unthunk, @thunk

julia> i = 10
10

julia> x = @thunk collect(1:i)[7:end]
Thunk(var"#5#6"())

julia> unthunk(x)
4-element Vector{Int64}:
  7
  8
  9
 10
```
https://github.com/JuliaDiff/ChainRulesCore.jl/blob/master/src/differentials/thunks.jl

**Comment by tbenst** [comment]
@mcabbott neat, thanks! I haven't looked into ChainRules yet--does it's thunk implementation obviate the need for this package?

Edit: I think a key difference is ChainRules thunk is quite pure and doesn't attempt to cache. [Basically `:(Thunk(() -> $(esc(body))))` but use the location where it is defined.](https://github.com/JuliaDiff/ChainRulesCore.jl/blob/1014715a38a0f5a9c1e84a804fb1b289e7fb760f/src/differentials/thunks.jl#L126)


As a result ChainRules thunk doesn't support DAGs of thunks, which is a goal here
```julia
julia> i = @thunk identity(10)
Thunk(var"#5#6"())

julia> x = @thunk collect(1:i)[7:end]
Thunk(var"#7#8"())

julia> unthunk(x)
ERROR: MethodError: no method matching (::Colon)(::Int64, ::ChainRulesCore.Thunk{var"#5#6"})
Closest candidates are:
  (::Colon)(::T, ::Any, ::T) where T<:Real at range.jl:41
  (::Colon)(::A, ::Any, ::C) where {A<:Real, C<:Real} at range.jl:10
  (::Colon)(::T, ::Any, ::T) where T at range.jl:40
  ...
Stacktrace:
 [1] (::var"#7#8")()
   @ Main ./REPL[5]:1
 [2] unthunk(x::ChainRulesCore.Thunk{var"#7#8"})
   @ ChainRulesCore ~/.julia/packages/ChainRulesCore/Voykb/src/differentials/thunks.jl:189
 [3] top-level scope
   @ REPL[6]:1
```

**Comment by mcabbott** [comment]
Haven't compared them in any depth, just randomly saw this example & thought it would work. Agree CR doesn't try to handle the case you describe, although perhaps it ought to think about allowing such things.
